name: stochastic-volcanoes
channels:
  - chrisroadmap
  - conda-forge
dependencies:
  - python==3.11
  - fair==2.1.3
  - jupyter
  - matplotlib
  - nbstripout
  - netcdf4
  - numpy
  - pandas
  - pooch
  - scipy
  - tqdm
